// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db_sqlc

import ()

type Daily struct {
	ID     int64
	Userid int64
	Name   string
}

type DailyLog struct {
	ID       int64
	Dailyid  int64
	Done     bool
	Datetime int64
}

type Habit struct {
	ID      int64
	Userid  int64
	Name    string
	Hasup   bool
	Hasdown bool
}

type HabitLog struct {
	ID        int64
	Habitid   int64
	Upcount   int64
	Downcount int64
	Datetime  int64
}

type Session struct {
	Token  string
	Userid int64
}

type User struct {
	ID           int64
	Username     string
	Passwordhash string
}
