// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db_sqlc

import (
	"context"
)

const addHabit = `-- name: AddHabit :one
INSERT INTO habits (
  userId, name, hasUp, hasDown
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, userid, name, hasup, hasdown
`

type AddHabitParams struct {
	Userid  int64
	Name    string
	Hasup   bool
	Hasdown bool
}

func (q *Queries) AddHabit(ctx context.Context, arg AddHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, addHabit,
		arg.Userid,
		arg.Name,
		arg.Hasup,
		arg.Hasdown,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Name,
		&i.Hasup,
		&i.Hasdown,
	)
	return i, err
}

const addHabitLog = `-- name: AddHabitLog :one
INSERT INTO habitLog (
  habitId, upCount, downCount, dateTime
) VALUES (
  ?, 0, 0, ?
)
RETURNING id, habitid, upcount, downcount, datetime
`

type AddHabitLogParams struct {
	Habitid  int64
	Datetime int64
}

func (q *Queries) AddHabitLog(ctx context.Context, arg AddHabitLogParams) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, addHabitLog, arg.Habitid, arg.Datetime)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.Habitid,
		&i.Upcount,
		&i.Downcount,
		&i.Datetime,
	)
	return i, err
}

const addSession = `-- name: AddSession :one
INSERT INTO sessions (
  token, userId
) VALUES (
  ?, ?
)
RETURNING token, userid
`

type AddSessionParams struct {
	Token  string
	Userid int64
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, addSession, arg.Token, arg.Userid)
	var i Session
	err := row.Scan(&i.Token, &i.Userid)
	return i, err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users (
  username, passwordHash
) VALUES (
  ?, ?
)
`

type AddUserParams struct {
	Username     string
	Passwordhash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Username, arg.Passwordhash)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, userid, name, hasup, hasdown FROM habits
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHabit(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Name,
		&i.Hasup,
		&i.Hasdown,
	)
	return i, err
}

const getHabitLog = `-- name: GetHabitLog :one
SELECT id, habitid, upcount, downcount, datetime from habitLog
WHERE habitId = ? and dateTime = ?
LIMIT 1
`

type GetHabitLogParams struct {
	Habitid  int64
	Datetime int64
}

func (q *Queries) GetHabitLog(ctx context.Context, arg GetHabitLogParams) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, getHabitLog, arg.Habitid, arg.Datetime)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.Habitid,
		&i.Upcount,
		&i.Downcount,
		&i.Datetime,
	)
	return i, err
}

const getHabits = `-- name: GetHabits :many
SELECT id, userid, name, hasup, hasdown FROM habits 
WHERE userId = ?
`

func (q *Queries) GetHabits(ctx context.Context, userid int64) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getHabits, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Name,
			&i.Hasup,
			&i.Hasdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitsAndLogs = `-- name: GetHabitsAndLogs :many
SELECT habits.id, habits.userid, habits.name, habits.hasup, habits.hasdown, hl.id, hl.habitid, hl.upcount, hl.downcount, hl.datetime FROM habits 
JOIN habitLog hl ON hl.habitId = habits.ID
WHERE habits.userId = ?
`

type GetHabitsAndLogsRow struct {
	Habit    Habit
	HabitLog HabitLog
}

func (q *Queries) GetHabitsAndLogs(ctx context.Context, userid int64) ([]GetHabitsAndLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitsAndLogs, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitsAndLogsRow
	for rows.Next() {
		var i GetHabitsAndLogsRow
		if err := rows.Scan(
			&i.Habit.ID,
			&i.Habit.Userid,
			&i.Habit.Name,
			&i.Habit.Hasup,
			&i.Habit.Hasdown,
			&i.HabitLog.ID,
			&i.HabitLog.Habitid,
			&i.HabitLog.Upcount,
			&i.HabitLog.Downcount,
			&i.HabitLog.Datetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT users.id, users.username, users.passwordhash FROM sessions
JOIN users ON users.ID = sessions.userId 
WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Passwordhash)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, passwordhash FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Passwordhash)
	return i, err
}

const habitLogDown = `-- name: HabitLogDown :one
UPDATE habitLog
SET downCount = downCount + 1
WHERE habitId = ? AND dateTime = ?
RETURNING id, habitid, upcount, downcount, datetime
`

type HabitLogDownParams struct {
	Habitid  int64
	Datetime int64
}

func (q *Queries) HabitLogDown(ctx context.Context, arg HabitLogDownParams) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, habitLogDown, arg.Habitid, arg.Datetime)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.Habitid,
		&i.Upcount,
		&i.Downcount,
		&i.Datetime,
	)
	return i, err
}

const habitLogUp = `-- name: HabitLogUp :one
UPDATE habitLog
SET upCount = upCount + 1
WHERE habitId = ? AND dateTime = ?
RETURNING id, habitid, upcount, downcount, datetime
`

type HabitLogUpParams struct {
	Habitid  int64
	Datetime int64
}

func (q *Queries) HabitLogUp(ctx context.Context, arg HabitLogUpParams) (HabitLog, error) {
	row := q.db.QueryRowContext(ctx, habitLogUp, arg.Habitid, arg.Datetime)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.Habitid,
		&i.Upcount,
		&i.Downcount,
		&i.Datetime,
	)
	return i, err
}
